sudo: false
language: rust
matrix:
  fast_finish: true
  include:
  - rust: nightly
  - rust: beta
  - rust: stable
script:
- cargo clean -v
- RUSTFLAGS="$RUSTFLAGS -C link-dead-code" cargo test
cache:
  cargo: true
  apt: true
  directories:
  - target/debug/deps
  - target/debug/build
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  curl -L https://github.com/SimonKagstrom/kcov/archive/master.tar.gz | tar xz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  make install DESTDIR=../tmp &&
  cd ../.. &&
  ls target/debug &&
  for file in target/debug/scuttlebutt-*; do mkdir -p "target/cov/$(basename $file)"; ./kcov-master/tmp/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  echo "covered" &&
  cargo doc --no-deps &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  echo "documented"
env:
  global:
    secure: DzjCwZae6k/GyYLJ5x3wgDIjO8SjzkAq3eI8RvRT4aqSfVai2x3y4bPk5QoX+lt6TLaJxmoc1Vq6HZJbNlKokpGAvyzwJ0qmCBWYCUcRyTUyAVmH8VEY/wnBF0k8lYiQmfxOeGhiQb8nHZSpIIhItfIUirKMXyCW3ArkVV5HzQa53T1mO3unY9AEnDgyHfmwke0QM6MYdHAhNjfg45dvckU6Euu2oAXZ0tQpf0+uDPpU78Mg3dJ523/REuhKgRjreHt3S99R8rmnlKY9ZQeK0Zg4ZE4e+xxeC0H67CIhLWZiIwqZxauA7zB11UXI7GZ6fZoPsvZN3U3TlJwaAU/RHzGBczZVxGqgujwsbrne2WRYFtnFirs8D15uRp4ix4UIyKaUeqy5rUoZcLAzKIWDNLTJ5bQvyhDN641eF1auPURr0z7g+tQc8uEEKmuJXR+PplHPzvGOTz54dQa603XeEoERjL/59XqcbJFCoW3FqIxlLMosBOyQBfE1eGpkisFUdZ6YYODEFFOggF1JWF5psP9DUJ9CX852EdPpgIzojvmo9KqeeBiHw/I02rTRa6QgsIT0uea5HlV6eNo0le9AeT3fMYfVU/wzDJxH/2mt42SCvLSbbXl9Nam1KUtEvjc5cGhD4vjnX6G2hAiY/xPXuvmlZ8btwlaykeI//wdvq7o=
